### ISSUE TITLE
Common or Global Variables

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [dynatrace-oss/dynatrace-monitoring-as-code#110]
**Is your feature request related to a problem? Please describe.**
It's feasible that multiple configurations could warrant the same values. For example, an `auto-tag` rule and an `application` could share the same name.

**Describe the solution you'd like**
A file where we can define these globals which are shared across all projects and configuration types.

For example:
**globals.yaml**
```
foo: "bar"
```

Then applications.yaml
```
config:
  - my_application: "application.json"

my_application:
  - name: "{{ .Globals.foo }}"
```

**Describe alternatives you've considered**
This is possible now via environment variables but that means we lose the ability to track these globals as variables that are committed to Git.
