### ISSUE TITLE
Cannot handle replaying configuration when CSM already exists

### ISSUE THREAD

**Issue by 163a** [dynatrace-oss/dynatrace-monitoring-as-code#124]
Monaco cannot handle replaying configuration when calcuated service metric (CSM) already exists.

Monaco returns `ERROR Deployment to {env} failed with error Failed to upsert DT object {metric-name} (HTTP 400)!`

```
Response was: {"error":{"code":400,"message":"Constraints violated.","constraintViolations":[{"path":"id","message":"metricKey in payload, if given, must match metricKey in URL","parameterLocation":"PAYLOAD_BODY","location":null},{"path":"name","message":"Metric name already used","parameterLocation":"PAYLOAD_BODY","location":null}]}}, responsible config:
...
```

JSON
```
{
  "tsmMetricKey": "{{ .metric_key }}",
  "name": "{{ .name }}",
  "enabled": {{ .enabled }},
  "metricDefinition": {
    "metric": "{{ .metric_type }}",
    "requestAttribute": null
  },
  "unit": "{{ .metric_unit }}",
  "unitDisplayName": null,
  "entityId": null,
  "managementZones": [],
  "conditions": [
    {
      "attribute": "SERVICE_TYPE",
      "comparisonInfo": {
        "type": "SERVICE_TYPE",
        "comparison": "EQUALS",
        "value": "WEB_REQUEST_SERVICE",
        "negate": false
      }
    },
    {
      "attribute": "SERVICE_REQUEST_ATTRIBUTE",
      "comparisonInfo": {
        "type": "STRING_REQUEST_ATTRIBUTE",
        "comparison": "{{ .match_operator }}",
        "value": null,
        "negate": false,
        "requestAttribute": "{{ .request_attribute }}",
        "caseSensitive": false,
        "matchOnChildCalls": false,
        "source": null
      }
    }
  ],
  "dimensionDefinition": {
    "name": "Dimension",
    "dimension": "{Request:Name} (HTTP Method={HTTP-Method}, Status={HTTP-Status})",
    "placeholders": [],
    "topX": 100,
    "topXDirection": "DESCENDING",
    "topXAggregation": "{{ .metric_topx_aggregation }}"
  }
}
```

YAML
```
config:
  - mymetric_request_count: "request_single_attribute.json"
  - mymetric_response_time: "request_single_attribute.json"

mymetric_request_count:
  - name: "My Req Attr Request Count"
  - enabled: "true"
  - request_attribute: "My Req Attr"
  - match_operator: "EXISTS"
  - metric_key: "calc:service.mymetric.request.count"
  - metric_type: "REQUEST_COUNT"
  - metric_unit: "COUNT"
  - metric_topx_aggregation: "SINGLE_VALUE"

mymetric_response_time:
  - name: "My Req Attr Response Time"
  - enabled: "true"
  - request_attribute: "My Req Attr"
  - match_operator: "EXISTS"
  - metric_key: "calc:service.mymetric.response.time"
  - metric_type: "RESPONSE_TIME"
  - metric_unit: "MICRO_SECOND"
  - metric_topx_aggregation: "AVERAGE"
```
