### ISSUE TITLE
Referencing for a specific environment doesn't work

### ISSUE THREAD

**Issue by IgnacioGoldman** [dynatrace-oss/dynatrace-monitoring-as-code#141]
(Monaco version v1.1.0)

My structure:
```
root/
  A/
    management-zone/
    dashboard/     
  B/
   ...   
  C/
   ...    
environment.yaml

```
I'm basically creating MZ, and then a dashboard using the MZ as a filter. I have to do that for 6 tenants at a time.
The creation of the MZ works fine. I have issues when creating the Dashboards

If i specify my dashboard.yaml in the following way, it works fine:green_heavy_check_mark:
```
config:
  - CDNewComponent: ApplicationXYZ.json

CDNewComponent:
  - name: CD_NewComponent
  - mzName: "00_Component-Template/management-zone/CDNewComponent.name"
  - mzId: "00_Component-Template/management-zone/CDNewComponent.id"

```
The problem comes when i specify it for a specific tenant, adding the ".EMEA-Prod"
```
config:
  - CDNewComponent: ApplicationXYZ.json

CDNewComponent.EMEA-Prod:
  - name: CD_NewComponent
  - mzName: "00_Component-Template/management-zone/CDNewComponent.name"
  - mzId: "00_Component-Template/management-zone/CDNewComponent.id"

```
This is the error i'm getting:
```
ERROR Deployment to EMEA-Prod failed with error Failed to upsert DT object CD_NewComponent (HTTP 400)!
    Response was: {"error":{"code":400,"message":"Could not map JSON at 'dashboardMetadata.dashboardFilter.managementZone.id' near line 12 column 9"}}, responsible config: Dynatrace-config\00_Component-Template\dashboard\ApplicationXYZ.json

```
