### ISSUE TITLE
Group has higher prio than environment

### ISSUE THREAD

**Issue by heydenb** [dynatrace-oss/dynatrace-monitoring-as-code#145]
**Describe the bug**
It seems to me that the group has a higher prio than environment when they are both defined in a yaml.

```
metric-commonapppool-request-contentlength.nonprod:
  - skipDeployment: "true"
  
metric-commonapppool-response-contentlength.nonprod:
  - skipDeployment: "true"
  
metric-commonapppool-request-contentlength.200REL:
  - name: Request ContentLength CommonAppPool 200REL
  - managementZoneName: 200REL
  
metric-commonapppool-response-contentlength.200REL:
  - name: Response ContentLength CommonAppPool 200REL
  - managementZoneName: 200REL
```

This is a part of my environments yaml
```
nonprod.200REL:
    - name: "200REL"
    - env-url: "https://xxxxx"
    - env-token-name: "NONPROD_TOKEN_ENV_VAR"
```

When executing for environment 200REL I would assume this beïng created and not skipped. At this moment it is skipped. This is documented the other way around

**Comment by heydenb** [comment]
Seems to work when I add skipDeployment: "false" explicitly at 200REL level

**Comment by tatomir146** [comment]
@heydenb this works as intended. All properties defined for configuration could also be overwritten on group or host level. In your example you have defined `skipDeployment` for the whole group of envs:
```
metric-commonapppool-request-contentlength.nonprod:
  - skipDeployment: "true"
```
and you have no overrides defined on env level:
```
metric-commonapppool-request-contentlength.200REL:
  - name: Request ContentLength CommonAppPool 200REL
  - managementZoneName: 200REL
  ```
  For this to work you then need, as stated in your second comment, to override `skipDeployment` parameter:
  ```
  metric-commonapppool-request-contentlength.200REL:
  - name: Request ContentLength CommonAppPool 200REL
  - managementZoneName: 200REL
  - skipDeployment: "false"
  ```
  We will try to make this more clear in the documentation.
