### ISSUE TITLE
Support for configuration endpoints that require a higher level configuration ID

### ISSUE THREAD

**Issue by kristofre** [dynatrace-oss/dynatrace-monitoring-as-code#147]
Some configurations require the ID of a _higher level_ configuration.
For example: Configuring key actions on a web application requires the web app id:
![image](https://user-images.githubusercontent.com/9797800/106291174-995cd800-624b-11eb-9f06-100f1899bbbb.png)

This is currently not supported by Monaco.
We need a mechanism that allows supplying the higher level entity ID - including via references within Monaco.

In the yaml file this could look then like this (example for web app key actions):

```
config:
    - key-action-one: "key-action-one.json"
  
key-action-one:
    - name: "key-action-one"
    - web-app-id: "/project-one/application/mywebapp.id"
```

Alternatively, we could make the name of the property generic if that makes sense (e.g.: "master-config").
