### ISSUE TITLE
Support specifying "real" booleans (not strings) in yaml files

### ISSUE THREAD

**Issue by didiladi** [dynatrace-oss/dynatrace-monitoring-as-code#25]
If a property defined in the yaml is a boolean, it feels counter-intuitive to write it as a string like: `"true"`. This already caused confusion for a customer.

The following should be possible:
```
config:
  - email: "email.json"
email:
  ...
  - enabled: true
```

Instead of:

```
config:
  - email: "email.json"
email:
  ...
  - enabled: "true"
```
