### ISSUE TITLE
References not working using relative paths

### ISSUE THREAD

**Issue by tatomir146** [dynatrace-oss/dynatrace-monitoring-as-code#307]
**Describe the bug**
If multiple relative dependencies are defined, according to log output (has dep on) only first is validated causing validation to fail.

**How to reproduce**
- Yaml config

```
notification-dev:
  - name: "Notifications example"
  - managementZoneName: "management-zone/dev.name"
  - alertingProfileId: "alerting-profile/platform-dev.id"
```

In this case only notification-dev is logged to have dep on management-zone but not alerting profile.

**Expected behavior**
Also alerting-profile should be logged.
