### ISSUE TITLE
Simplify configuration

### ISSUE THREAD

**Issue by tatomir146** [dynatrace-oss/dynatrace-monitoring-as-code#351]
### Discussed in https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/discussions/165

<div type='discussions-op-text'>

<sup>Originally posted by **tatomir146** February  3, 2021</sup>
Currently configuration definition is done in 2 sections: 

1. define a config id and map json to it
2. use this id to define additional configuration parameters

Wouldn't it be easier and also more readable to have something like this:
```
my-cool-config:
  template: "my-cool-config.json"
  name: "Here some cool name"
  skipDeployment: true
  params: 
    - some-param: "Never enough of coolness"
    - another-param: "Yet another param"
```
We already have name and skipDeployment as reserved params but this is not visible in configuration, you need to take a look in documentation for this. IMO it would help us to adapt YAML structure and have these params on the first level and define all custom params within e.g. "params". This would simplify our parsing logic.

Then we could also think about defining references in more flexible way which should simplify resolving dependencies:
```
more-config:
  template: "template.json"
  name: "We need a name"
  params: 
    - some-reference: 
         project: "some project"
         api: "custom-service"
         configId: "custom-service-config-id"
  # or relative to project
   - another-reference:
        api: "extension"
        configId: "extension-config-id"
```
In case there is a reference we map *all* parameters including name and id and then we can use this object within json template:
```
{
 "name": {{ .name }},
 "id": {{ .some-reference.id }}"
 "anotherReference": {{ .some-reference.whatever }}
}
```

Please also notice changes in YAML data types.</div>
