### ISSUE TITLE
request-naming-service and monaco not working well together

### ISSUE THREAD

**Issue by heydenb** [dynatrace-oss/dynatrace-monitoring-as-code#377]
We defined a Global request naming rule using the API and this works fine. But when putting it in our monaco configuration it is recreated every time monaco runs.
The reason for this is that this API does not take a name attribute. So monaco probably doesn't know if it already exists or not. Giving it an "id" is also not accepted.

**Comment by tatomir146** [comment]
@heydenb can you please give us an example of the yaml and JSON config used in this case?

**Comment by heydenb** [comment]
```
config:
  - schedulerJobRequestNaming: "scheduler-job-request-naming.json"
  - rmiProxyRequestNaming: "rmiproxy-request-naming.json"

schedulerJobRequestNaming:
  - name: "Scheduler Job Request Naming Rule"

rmiProxyRequestNaming:
  - name: "RMIProxy Request Naming Rule"
  - requestAttrProxyService: "projects/scheduler/request-attributes/rmiProxyCallService.name"
  - requestAttrProxyMethod: "projects/scheduler/request-attributes/rmiProxyCallMethod.name"
```

and

```
{
    "name": "{{.name}}",
    "order": "1",
    "enabled": true,
    "namingPattern": "{RequestAttribute:SchedulerJobName}",
    "conditions": [
        {
            "attribute": "SERVICE_REQUEST_ATTRIBUTE",
            "comparisonInfo": {
              "type": "STRING_REQUEST_ATTRIBUTE",
              "comparison": "EXISTS",
              "requestAttribute": "SchedulerJobName",
              "negate": false,
              "isCaseSensitive": false
            }
        },
        {
            "attribute": "CUSTOMSERVICE_CLASS",
            "comparisonInfo": {
            "type": "STRING",
            "comparison": "CONTAINS",
            "value": "JobViaRest",
            "negate": false,
            "isCaseSensitive": false
            }
        }
    ],
    "placeholders": []
  }
```

**Comment by afri33** [comment]
It's not a solution, but it is maybe a small workaround/helpful in some cases. I could also make updates to an existing rule if name and namingPattern are the same. Example:

```
config:
    - demo-rule: "request-naming-service.json"
  
demo-rule:
    - name: "/demo/v1/<COUNTRY>/demo"
    - namingPattern: "/demo/v1/<COUNTRY>/demo"
```

Name is not part of the API body (request naming object) - https://www.dynatrace.com/support/help/shortlink/api-request-naming-post-new#body-format. NamingPattern is used as display name in Dynatrace.
However, this "workaround" does not always work. If the naming pattern changes due to a customization of the rule, a new rule may be created instead of customizing the original one.
