### ISSUE TITLE
YAML Parsing - Failure to parse list of synthetic locations

### ISSUE THREAD

**Issue by chrisorisawayi** [dynatrace-oss/dynatrace-monitoring-as-code#400]
**Describe the bug**
Unable to parse list of synthetic locations in a yaml file location variable.

**How to reproduce**
- Yaml config: [copied from sample project](https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/blob/main/cmd/monaco/test-resources/integration-all-configs/project/synthetic-monitor/synthetic-monitors.yaml).
``` yaml
config: 
  - availability: "availabilty.json"

availability:
  - name: "Federation Availability"
  - location:
    - "GEOLOCATION-9999453BE4BDB3CD"
    - "GEOLOCATION-E7F41460B2A0E4B3"
  - managementZoneId: ""
  - tag: ""
  - host: "https://www.google.com"
```
OR
``` yaml
config: 
  - availability: "availabilty.json"

availability:
  - name: "Federation Availability"
  - location:
      - "GEOLOCATION-9999453BE4BDB3CD"
      - "GEOLOCATION-E7F41460B2A0E4B3"
  - managementZoneId: ""
  - tag: ""
  - host: "https://www.google.com"
```
OR
``` yaml
config: 
  - availability: "availabilty.json"

availability:
  - name: "Federation Availability"
  - location: [
    "GEOLOCATION-9999453BE4BDB3CD",
    "GEOLOCATION-E7F41460B2A0E4B3"
    ]
  - managementZoneId: ""
  - tag: ""
  - host: "https://www.google.com"
```

- JSON template: [copied from sample project](https://github.com/dynatrace-oss/dynatrace-monitoring-as-code/blob/main/cmd/monaco/test-resources/integration-all-configs/project/synthetic-monitor/availabilty.json)
``` json
{
  "name": "{{ .name }}",
  "frequencyMin": 2,
  "enabled": true,
  "type": "HTTP",
  "script": {
    "version": "1.0",
    "requests": [
      {
        "description": "check-redis Endpoint",
        "url": "{{ .host }}/admin/health/check-redis",
        "method": "GET",
        "requestBody": "",
        "validation": {
          "rules": [
            {
              "value": ">=400",
              "passIfFound": false,
              "type": "httpStatusesList"
            }
          ]
        },
        "configuration": {
          "acceptAnyCertificate": true,
          "followRedirects": true
        }
      }
    ]
  },
  "locations": [
    "{{ .location }}"
  ],
  "anomalyDetection": {
    "outageHandling": {
      "globalOutage": true,
      "localOutage": false,
      "localOutagePolicy": {
        "affectedLocations": 1,
        "consecutiveRuns": 3
      }
    },
    "loadingTimeThresholds": {
      "enabled": false,
      "thresholds": [
        {
          "type": "TOTAL",
          "valueMs": 0
        }
      ]
    }
  },
  "tags": [
    "{{.tag}}"
  ],
  "managementZones": [
    "{{.managementZoneId}}"
  ],
  "manuallyAssignedApps": []
}
```
- Flags used to execute tool
```
--dry-run -v
```
**Expected behavior**
Running monaco deploy --dry-run -v on the json/yaml files location should indicate 'validation finishes without errors'.  The above yaml files are verified with yaml linters as valid yaml.

**Log output**
```
FATAL YAML file synthetic-monitors.yaml could not be parsed: cannot convert YAML
```

**Environment (please complete the following information):**
 - OS: [macOs BigSur, Ubuntu 18.04]
 - Tool version [e.g. 1.5.3]

**Additional context**
Passing multiple hardcoded synthetic locations in the json file as below works. But using a variable in the json provides more flexibility and allows multiple configs with different synthetic location requirements share the same json template.
``` json
{
  "name": "{{ .name }}",
  "frequencyMin": 2,
  "enabled": true,
  "type": "HTTP",
  "script": {
    "version": "1.0",
    "requests": [
      {
        "description": "check-redis Endpoint",
        "url": "{{ .host }}/admin/health/check-redis",
        "method": "GET",
        "requestBody": "",
        "validation": {
          "rules": [
            {
              "value": ">=400",
              "passIfFound": false,
              "type": "httpStatusesList"
            }
          ]
        },
        "configuration": {
          "acceptAnyCertificate": true,
          "followRedirects": true
        }
      }
    ]
  },
  "locations": [
    "GEOLOCATION-9999453BE4BDB3CD",
    "GEOLOCATION-E7F41460B2A0E4B3"
  ],
  "anomalyDetection": {
    "outageHandling": {
      "globalOutage": true,
      "localOutage": false,
      "localOutagePolicy": {
        "affectedLocations": 1,
        "consecutiveRuns": 3
      }
    },
    "loadingTimeThresholds": {
      "enabled": false,
      "thresholds": [
        {
          "type": "TOTAL",
          "valueMs": 0
        }
      ]
    }
  },
  "tags": [
    "{{.tag}}"
  ],
  "managementZones": [
    "{{.managementZoneId}}"
  ],
  "manuallyAssignedApps": []
}
```
Also checked through all examples in the cmd/monaco/test-resources folder and noticed there are no examples passing a list as value to a variable.

**Comment by beeme1mr** [comment]
I'm running into this exact issue. Is it possible to pass a list to a property in the YAML file?

**Comment by patrickpichler** [comment]
Sadly it is currently not possible to pass in a list property. 
But with config v2, which is currently in preview in the `next` branch
this will be possible to have more complex values as just strings. 

There is no concrete ETA until v2 is done though.

**Comment by beeme1mr** [comment]
It's a bit ugly but I was able to get around this issue by combining all the locations into a single string value.

```yaml
config: 
  - availability: "availabilty.json"

availability:
  - name: "Availability Test"
  - locations: 'GEOLOCATION-9999453BE4BDB3CD", "GEOLOCATION-E7F41460B2A0E4B3'
```
```json
{
  ...
  "locations": ["{{ .locations }}"],
  ...
}
```
