### ISSUE TITLE
Duplicate Deployments for Dashboards

### ISSUE THREAD

**Issue by zenobios** [dynatrace-oss/dynatrace-monitoring-as-code#411]
Hi,

while I'm playing around with monaco I probably found a bug regarding the deployment of dashboards. Im using the following files (pleas adapt <FILL> with values matching your dynatrace instance):

`environments.yaml`:
```
dev:
  - name: "DEV"
  - env-url: "<FILL>"
  - env-token-name: "DYN_TOKEN"
```

`dev/dashboard/config.yaml`:
```
config:
  - Dashboard: "Dashboard.json"

Dashboard:
  - name: Dashboard Test
```

`dev/dashboard/Dashboard.json`:
```
{
  "dashboardMetadata": {
    "name": "{{.name}}",
    "shared": true,
    "owner": "<FILL>"
  },
  "tiles": [
    {
      "name": "Header",
      "tileType": "HEADER",
      "configured": true,
      "bounds": {
        "top": 0,
        "left": 0,
        "width": 304,
        "height": 38
      },
      "tileFilter": {}
    }
  ]
}
```

Observed behaviour: When I deploy this configuration multiple times, multiple dashboards will be created. 

Expected behaviour: Dashboard will be created if it's not existing yet, otherwise it will be updated.
