### ISSUE TITLE
Reference validation

### ISSUE THREAD

**Issue by gal-pal** [dynatrace-oss/dynatrace-monitoring-as-code#488]
The validation for the selected environment probably checks also configuration of other environments.
In some cases it may display error regarding non-existing references for skipped configurations. 

E.g.
./monaco -dry-run -e=synthetic/tenants.yaml -se=dev -p=general synthetic

Content of dashboard.yaml
```
config:
    - dashboard-main: "dashboard-main.json"
dashboard-main:
    - name: "Synthetic Main"
dashboard-main.dev:
    - syntheticControlSyntheticTestId: "/general/synthetic-monitor/SyntheticControl20-availability.id"
dashboard-main.prod:
    - syntheticControlSyntheticTestId: "/general/synthetic-monitor/SyntheticControl20-clickpath.id"
```

Content of synthetic-monitor.yaml
```
config:
    - SyntheticControl20-clickpath: "SyntheticControl20-clickpath.json"
    - SyntheticControl20-availability: "SyntheticControl20-availability.json"
    
SyntheticControl20-clickpath:
    - name: "Synthetic Control 2.0 "
    - skipDeployment: "true"  
SyntheticControl20-clickpath.prod:
    - skipDeployment: "false"    
    
SyntheticControl20-availability:
    - name: "Synthetic Control 2.0"
    - skipDeployment: "true"
SyntheticControl20-availability.dev:
    - skipDeployment: "false"
```
    
**Log output**
Dynatrace Monitoring as Code v1.6.0
Executing projects in this order: 
1: synthetic/general (10 configs)
Processing environment **dev**...
Processing project synthetic/general...
skipping deployment of SyntheticControl20-clickpath: synthetic/general/synthetic-monitor/SyntheticControl20-clickpath.json
Failed Id 'general/synthetic-monitor/SyntheticControl20-clickpath' was not available. Please make sure the reference exists.

SyntheticControl20-clickpath.json is used for prod environment and the reference not exists, but I executed dry-run for dev environment.

**Environment **
 - Tool version 1.6.0

**Comment by krzema12** [comment]
The same goes for environment variables resolution. E.g. I have

```
Sth.dev:
  - username: "{{ .Env.ENV_VAR_DEV }}"
Sth.prod:
  - username: "{{ .Env.ENV_VAR_PROD }}"
```

If I want to deploy only one of them, now I need to set environment variables for all of the remaining ones which is pretty annoying.
