### ISSUE TITLE
Allow configuration loops

### ISSUE THREAD

**Issue by tatomir146** [dynatrace-oss/dynatrace-monitoring-as-code#8]
It should be possible to define one configuration and apply it n times:
```
autotagging:
  - name: "Cluster[1..45]"
  - tag: "ClusterTag[1..45]"
  - process-group-name:
    - 1: "cluster_prod1-john"
    - 2: "cluster_prod2-mike"
    - 3: "cluster_prod3-tom"
    - 4: "cluster_prod4-michael"
      ...
    - 45: "cluster_prod45-whatsoever"
```
Counters `[1..45]` and lists should be supported:
```
- process-group-name:
    - 1: "cluster_prod1-john"
    - 2: "cluster_prod2-mike"
    - 3: "cluster_prod3-tom"
    - 4: "cluster_prod4-michael"
```
Allowed are only positive numbers. Counter doesn't have to start with 1.
Counters can be also defined as:
```
- name: "[1..45] Test"
```
or
```
- name: "Configuration [1..45] something"
```
Only one counter per parameter is allowed

`name` parameter defines how often is configuration applied and takes on every iteration it's incremental value:
name: "Test [1..45]" has following values: `Test 1`, `Test 2` ... `Test 45`
If configuration parameters contains counter or list, and name doesn't, then config validation should fail:
```
autotagging:
  - name: "Cl-Prod"
  - tag: "Cluster[1..45]"
  - process-group-name:
    - 1: "cluster_prod1-john"
    - 2: "cluster_prod2-mike"
    - 3: "cluster_prod3-tom"
    - 4: "cluster_prod4-michael"
```
The counter size or number of elements in the list must match for all parameters. Something like this is not allowed:
```
  - name: "Cl-Prod"
  - tag: "Cluster[1..40]"
  - process-group-name:
    - 1: "cluster_prod1-john"
    - 2: "cluster_prod2-mike"
    - 3: "cluster_prod3-tom"
    - 4: "cluster_prod4-michael"
```
